### ISSUE TITLE
NGINX Module

### ISSUE THREAD

**Issue by MiguelFGM** [janbar/ipfilter#2]
After compiling ipfilter I get on console that ngx_http_ipfilter_module.so has been generated on the obj of the path that I choose, but the file is never generated.

Wouldn't be more flexible if the NGINX module is separated from the ipfilter itself and we compile NGINX directly with it? Like testcookie or other modules.

**Comment by janbar** [comment]
You can do that, regarding the file CMakeLists.txt:

```
  add_custom_command(
    OUTPUT  ${NGINX_SOURCE_DIR}/objs/${LIB_NGX_MODULE}
    WORKING_DIRECTORY ${NGINX_SOURCE_DIR}
    COMMAND ./configure --with-compat --add-dynamic-module=${PROJECT_SOURCE_DIR}
    COMMAND make modules)
```
So from the source of NGINX, you have to run:

```
./configure --with-compat --add-dynamic-module=${IPFILTER_SOURCE_DIR}
make modules
```

Isn't it ?

**Comment by MiguelFGM** [comment]
Getting:
2024/01/30 11:10:13 [alert] 239318#239318: worker process 239321 exited on signal 11 (core dumped)

While loading it with "load_module"

I'm using OpenResty latest version.

**Comment by MiguelFGM** [comment]
Sorry, seems like the core dumped just happens while using: "ipfilter_denied_url", if I use the variables it works just fine
